<?php
/**
 * Controller
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use Psr\Log\LoggerInterface;
use Psr\Container\ContainerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Swagger\Server\Service\SerializerInterface;
use Swagger\Server\Api\ApiServer;
use Swagger\Server\Service\JmsSerializer;
use Swagger\Server\Service\SymfonyValidator;

/**
 * Controller Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Controller extends AbstractController
{
    protected $validator;
    protected $serializer;
    protected $apiServer;
    protected $logger;

    public function __construct(
        ContainerInterface $container,
        LoggerInterface $logger,
        JmsSerializer $serializer,
        SymfonyValidator $validator,
        ApiServer $apiServer
    ) {
        $this->setContainer($container); // ✅ Correct way to set the container
        $this->logger = $logger;
        $this->serializer = $serializer;
        $this->validator = $validator;
        $this->apiServer = $apiServer;
    }

    public function setSerializer(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    public function setApiServer($server)
    {
        $this->apiServer = $server;
    }

    /**
     * Serializes data to a given type format.
     *
     * @param mixed  $data   The data to serialize.
     * @param string $class  The source data class.
     * @param string $format The target serialization format.
     *
     * @return string A serialized data string.
     */
    protected function serialize($data, $format)
    {
        return $this->serializer->serialize($data, $format);
    }

    /**
     * Deserializes data from a given type format.
     *
     * @param string $data   The data to deserialize.
     * @param string $class  The target data class.
     * @param string $format The source serialization format.
     *
     * @return mixed A deserialized data.
     */
    protected function deserialize($data, $class, $format)
    {
        return $this->serializer->deserialize($data, $class, $format);
    }

    protected function validate($data, $asserts = null)
    {
        $errors = $this->validator->validate($data, $asserts);
        return (array)$errors->getIterator();
    }

    protected function formatValidationMessages($parameterName, $validationMessages) {
        $messages = [];
        foreach ($validationMessages as $message) {
            $formattedMessage = "{$parameterName}: {$message->getMessage()}";
            if ($message->getPropertyPath()) {
                $formattedMessage = "{$parameterName}.{$message->getPropertyPath()}: {$message->getMessage()}";
            }
            $messages[] = $formattedMessage;
        }
        return $messages;
    }

    /**
     * Converts an exception to a serializable array.
     *
     * @param \Exception|null $exception
     *
     * @return array
     */
    private function exceptionToArray(\Exception $exception = null)
    {
        if (null === $exception) {
            return null;
        }

        if (!$this->container->get('kernel')->isDebug()) {
            return [
                'message'  => $exception->getMessage(),
            ];
        }

        return [
            'message'  => $exception->getMessage(),
            'type'     => get_class($exception),
            'previous' => $this->exceptionToArray($exception->getPrevious()),
        ];
    }

    protected function sanitizeContentTypes($contentTypes) {
        return array_map(function ($value) {
            if (strpos($value, ';') === false) {
                return $value;
            }
            $splitValue = explode(';', $value);
            return array_shift($splitValue);
        }, $contentTypes);
    }

    protected function getOutputFormat($accept, array $produced)
    {
        $producedContentTypes = $this->sanitizeContentTypes($produced);
        // Figure out what the client accepts
        $accept = preg_split("/[\s,;]+/", $accept);

        if (in_array('*/*', $accept) || in_array('application/*', $accept)) {
            // Prefer JSON if the client has no preference
            if (in_array('application/json', $producedContentTypes)) {
                return 'application/json';
            }
            if (in_array('application/xml', $producedContentTypes)) {
                return 'application/xml';
            }
        }

        if (in_array('*/*', $accept)) {
            // Prefer HTML if the client has no preference
            if (in_array('text/html', $producedContentTypes)) {
                return 'text/html';
            }
        }

        if (in_array('application/json', $accept) && in_array('application/json', $producedContentTypes)) {
            return 'application/json';
        }

        if (in_array('application/xml', $accept) && in_array('application/xml', $producedContentTypes)) {
            return 'application/xml';
        }

        if (in_array('text/html', $accept) && in_array('text/html', $producedContentTypes)) {
            return 'text/html';
        }

        // If we reach this point, we don't have a common ground between server and client
        return null;
    }
}
