<?php

/**
 * PetController
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use \Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use Swagger\Server\Api\PetApiInterface;
use Psr\Log\LoggerInterface;
use Swagger\Server\Model\ApiResponse;
use Swagger\Server\Model\Pet;

/**
 * PetController Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PetController extends Controller
{

    /**
     * Operation addPet
     *
     * Add a new pet to the store
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function addPetAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'PetController::addPet']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            405 => [
                'message' => 'Invalid input',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            'application/json','application/xml',
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'Swagger\Server\Model\Pet', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts = null;
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->addPet($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'addPet');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'addPet');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'addPet');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::addPet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'addPet');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::addPet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'addPet');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::addPet']);
            return $responseObject;
        }
    }

    /**
     * Operation deletePet
     *
     * Deletes a pet
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function deletePetAction(Request $request, $petId)
    {
        $this->logger->info($request, ['operation' => 'PetController::deletePet']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            400 => [
                'message' => 'Invalid pet value',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $apiKey = $request->headers->get('api_key');

            // Deserialize the input values that needs it
            $petId = $this->deserialize($petId, 'int', 'string');
            $apiKey = $this->deserialize($apiKey, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("int");
            $errors = $this->validate($petId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('petId', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($apiKey, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('api_key', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->deletePet($petId, $apiKey, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'deletePet');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'deletePet');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'deletePet');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::deletePet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'deletePet');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::deletePet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'deletePet');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::deletePet']);
            return $responseObject;
        }
    }

    /**
     * Operation findPetsByStatus
     *
     * Finds Pets by status
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function findPetsByStatusAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'PetController::findPetsByStatus']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\Pet',
            ],
            400 => [
                'message' => 'Invalid status value',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $status = $request->query->get('status');

            // Deserialize the input values that needs it
            $status = $this->deserialize($status, 'array<csv,string>', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\All([
                new Assert\Choice([ "available", "pending", "sold" ])
            ]);
            $asserts[] = new Assert\All([
                new Assert\Type("string")
            ]);
            $errors = $this->validate($status, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('status', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->findPetsByStatus($status, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'findPetsByStatus');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'findPetsByStatus');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'findPetsByStatus');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::findPetsByStatus']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'findPetsByStatus');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::findPetsByStatus']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'findPetsByStatus');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::findPetsByStatus']);
            return $responseObject;
        }
    }

    /**
     * Operation findPetsByTags
     *
     * Finds Pets by tags
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function findPetsByTagsAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'PetController::findPetsByTags']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\Pet',
            ],
            400 => [
                'message' => 'Invalid tag value',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $tags = $request->query->get('tags');

            // Deserialize the input values that needs it
            $tags = $this->deserialize($tags, 'array<csv,string>', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\All([
                new Assert\Type("string")
            ]);
            $errors = $this->validate($tags, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('tags', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->findPetsByTags($tags, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'findPetsByTags');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'findPetsByTags');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'findPetsByTags');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::findPetsByTags']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'findPetsByTags');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::findPetsByTags']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'findPetsByTags');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::findPetsByTags']);
            return $responseObject;
        }
    }

    /**
     * Operation getPetById
     *
     * Find pet by ID
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function getPetByIdAction(Request $request, $petId)
    {
        $this->logger->info($request, ['operation' => 'PetController::getPetById']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\Pet',
            ],
            400 => [
                'message' => 'Invalid ID supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'Pet not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'api_key' required
            // Set key with prefix in header
            $securityapi_key = $request->headers->get('api_key');

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it
            $petId = $this->deserialize($petId, 'int', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("int");
            $errors = $this->validate($petId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('petId', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'api_key'
            $handler->setapi_key($securityapi_key);
            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->getPetById($petId, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'getPetById');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'getPetById');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'getPetById');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::getPetById']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'getPetById');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::getPetById']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'getPetById');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::getPetById']);
            return $responseObject;
        }
    }

    /**
     * Operation updatePet
     *
     * Update an existing pet
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function updatePetAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'PetController::updatePet']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            400 => [
                'message' => 'Invalid ID supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'Pet not found',
                'responseType' => '',
            ],
            405 => [
                'message' => 'Validation exception',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            'application/json','application/xml',
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'Swagger\Server\Model\Pet', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts = null;
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->updatePet($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'updatePet');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'updatePet');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'updatePet');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::updatePet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'updatePet');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::updatePet']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'updatePet');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::updatePet']);
            return $responseObject;
        }
    }

    /**
     * Operation updatePetWithForm
     *
     * Updates a pet in the store with form data
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function updatePetWithFormAction(Request $request, $petId)
    {
        $this->logger->info($request, ['operation' => 'PetController::updatePetWithForm']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            405 => [
                'message' => 'Invalid input',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $name = $request->request->get('');
            $status = $request->request->get('');

            // Deserialize the input values that needs it
            $petId = $this->deserialize($petId, 'int', 'string');
            $name = $this->deserialize($name, 'string', 'string');
            $status = $this->deserialize($status, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("int");
            $errors = $this->validate($petId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('petId', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($name, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('name', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($status, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('status', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->updatePetWithForm($petId, $name, $status, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'updatePetWithForm');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'updatePetWithForm');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'updatePetWithForm');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::updatePetWithForm']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'updatePetWithForm');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::updatePetWithForm']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'updatePetWithForm');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::updatePetWithForm']);
            return $responseObject;
        }
    }

    /**
     * Operation uploadFile
     *
     * uploads an image
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function uploadFileAction(Request $request, $petId)
    {
        $this->logger->info($request, ['operation' => 'PetController::uploadFile']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\ApiResponse',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'petstore_auth' required
            // Oauth required
            $securitypetstore_auth = $request->headers->get('authorization');

            // Read out all input parameter values into variables
            $additionalMetadata = $request->request->get('');
            $file = $request->files->get('');

            // Deserialize the input values that needs it
            $petId = $this->deserialize($petId, 'int', 'string');
            $additionalMetadata = $this->deserialize($additionalMetadata, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("int");
            $errors = $this->validate($petId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('petId', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($additionalMetadata, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('additionalMetadata', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\File();
            $errors = $this->validate($file, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('file', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'petstore_auth'
            $handler->setpetstore_auth($securitypetstore_auth);
            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->uploadFile($petId, $additionalMetadata, $file, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'uploadFile');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'uploadFile');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'uploadFile');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::uploadFile']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'uploadFile');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'PetController::uploadFile']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'uploadFile');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'PetController::uploadFile']);
            return $responseObject;
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return PetApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('pet');
    }
}
