<?php

/**
 * StoreController
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use \Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use Swagger\Server\Api\StoreApiInterface;
use Psr\Log\LoggerInterface;
use Swagger\Server\Model\Order;

/**
 * StoreController Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoreController extends Controller
{

    /**
     * Operation deleteOrder
     *
     * Delete purchase order by ID
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function deleteOrderAction(Request $request, $orderId)
    {
        $this->logger->info($request, ['operation' => 'StoreController::deleteOrder']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            400 => [
                'message' => 'Invalid ID supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'Order not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it
            $orderId = $this->deserialize($orderId, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($orderId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('orderId', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->deleteOrder($orderId, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'deleteOrder');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'deleteOrder');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'deleteOrder');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::deleteOrder']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'deleteOrder');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::deleteOrder']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'deleteOrder');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'StoreController::deleteOrder']);
            return $responseObject;
        }
    }

    /**
     * Operation getInventory
     *
     * Returns pet inventories by status
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function getInventoryAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'StoreController::getInventory']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'int',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication
            // Authentication 'api_key' required
            // Set key with prefix in header
            $securityapi_key = $request->headers->get('api_key');

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it

            // Validate the input values
            $validationMessages = [];
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            // Set authentication method 'api_key'
            $handler->setapi_key($securityapi_key);
            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->getInventory($responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'getInventory');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'getInventory');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'getInventory');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::getInventory']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'getInventory');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::getInventory']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'getInventory');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'StoreController::getInventory']);
            return $responseObject;
        }
    }

    /**
     * Operation getOrderById
     *
     * Find purchase order by ID
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function getOrderByIdAction(Request $request, $orderId)
    {
        $this->logger->info($request, ['operation' => 'StoreController::getOrderById']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\Order',
            ],
            400 => [
                'message' => 'Invalid ID supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'Order not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it
            $orderId = $this->deserialize($orderId, 'int', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("int");
            $asserts[] = new Assert\GreaterThanOrEqual(1);
            $asserts[] = new Assert\LessThanOrEqual(5);
            $errors = $this->validate($orderId, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('orderId', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->getOrderById($orderId, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'getOrderById');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'getOrderById');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'getOrderById');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::getOrderById']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'getOrderById');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::getOrderById']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'getOrderById');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'StoreController::getOrderById']);
            return $responseObject;
        }
    }

    /**
     * Operation placeOrder
     *
     * Place an order for a pet
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function placeOrderAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'StoreController::placeOrder']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\Order',
            ],
            400 => [
                'message' => 'Invalid Order',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'Swagger\Server\Model\Order', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts = null;
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->placeOrder($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'placeOrder');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'placeOrder');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'placeOrder');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::placeOrder']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'placeOrder');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'StoreController::placeOrder']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'placeOrder');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'StoreController::placeOrder']);
            return $responseObject;
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return StoreApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('store');
    }
}
