<?php

/**
 * UserController
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use \Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use Swagger\Server\Api\UserApiInterface;
use Psr\Log\LoggerInterface;
use Swagger\Server\Model\User;

/**
 * UserController Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserController extends Controller
{

    /**
     * Operation createUser
     *
     * Create user
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function createUserAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'UserController::createUser']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            0 => [
                'message' => 'successful operation',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'Swagger\Server\Model\User', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts = null;
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->createUser($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'createUser');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'createUser');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'createUser');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'createUser');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'createUser');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::createUser']);
            return $responseObject;
        }
    }

    /**
     * Operation createUsersWithArrayInput
     *
     * Creates list of users with given input array
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function createUsersWithArrayInputAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'UserController::createUsersWithArrayInput']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            0 => [
                'message' => 'successful operation',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'array<Swagger\Server\Model\User>', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\All([
                new Assert\Type("Swagger\Server\Model\User")
            ]);
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->createUsersWithArrayInput($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'createUsersWithArrayInput');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'createUsersWithArrayInput');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'createUsersWithArrayInput');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUsersWithArrayInput']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'createUsersWithArrayInput');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUsersWithArrayInput']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'createUsersWithArrayInput');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::createUsersWithArrayInput']);
            return $responseObject;
        }
    }

    /**
     * Operation createUsersWithListInput
     *
     * Creates list of users with given input array
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function createUsersWithListInputAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'UserController::createUsersWithListInput']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            0 => [
                'message' => 'successful operation',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $body = $this->deserialize($body, 'array<Swagger\Server\Model\User>', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\All([
                new Assert\Type("Swagger\Server\Model\User")
            ]);
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->createUsersWithListInput($body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'createUsersWithListInput');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'createUsersWithListInput');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'createUsersWithListInput');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUsersWithListInput']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'createUsersWithListInput');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::createUsersWithListInput']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'createUsersWithListInput');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::createUsersWithListInput']);
            return $responseObject;
        }
    }

    /**
     * Operation deleteUser
     *
     * Delete user
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function deleteUserAction(Request $request, $username)
    {
        $this->logger->info($request, ['operation' => 'UserController::deleteUser']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            400 => [
                'message' => 'Invalid username supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'User not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it
            $username = $this->deserialize($username, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($username, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('username', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->deleteUser($username, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'deleteUser');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'deleteUser');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'deleteUser');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::deleteUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'deleteUser');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::deleteUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'deleteUser');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::deleteUser']);
            return $responseObject;
        }
    }

    /**
     * Operation getUserByName
     *
     * Get user by user name
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function getUserByNameAction(Request $request, $username)
    {
        $this->logger->info($request, ['operation' => 'UserController::getUserByName']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'Swagger\Server\Model\User',
            ],
            400 => [
                'message' => 'Invalid username supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'User not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it
            $username = $this->deserialize($username, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($username, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('username', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->getUserByName($username, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'getUserByName');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'getUserByName');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'getUserByName');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::getUserByName']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'getUserByName');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::getUserByName']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'getUserByName');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::getUserByName']);
            return $responseObject;
        }
    }

    /**
     * Operation loginUser
     *
     * Logs user into the system
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function loginUserAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'UserController::loginUser']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            200 => [
                'message' => 'successful operation',
                'responseType' => 'string',
            ],
            400 => [
                'message' => 'Invalid username/password supplied',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $username = $request->query->get('username');
            $password = $request->query->get('password');

            // Deserialize the input values that needs it
            $username = $this->deserialize($username, 'string', 'string');
            $password = $this->deserialize($password, 'string', 'string');

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($username, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('username', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($password, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('password', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];
            $response = $handler->loginUser($username, $password, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'loginUser');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'loginUser');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'loginUser');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::loginUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'loginUser');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::loginUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'loginUser');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::loginUser']);
            return $responseObject;
        }
    }

    /**
     * Operation logoutUser
     *
     * Logs out current logged in user session
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function logoutUserAction(Request $request)
    {
        $this->logger->info($request, ['operation' => 'UserController::logoutUser']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            0 => [
                'message' => 'successful operation',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables

            // Deserialize the input values that needs it

            // Validate the input values
            $validationMessages = [];
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->logoutUser($responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'logoutUser');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'logoutUser');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'logoutUser');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::logoutUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'logoutUser');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::logoutUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'logoutUser');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::logoutUser']);
            return $responseObject;
        }
    }

    /**
     * Operation updateUser
     *
     * Updated user
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function updateUserAction(Request $request, $username)
    {
        $this->logger->info($request, ['operation' => 'UserController::updateUser']);
        // get the handler for the api first, we need it throughout the whole function
        $handler = $this->getApiHandler();

        // know response codes, models and messages
        $responses = [

            400 => [
                'message' => 'Invalid user supplied',
                'responseType' => '',
            ],
            404 => [
                'message' => 'User not found',
                'responseType' => '',
            ],
        ];

        // set response and format to null, we need the variable even when not set
        $response = null;
        $responseFormat = null;

        // Make sure that the client is providing something that we can consume
        $consumes = [
            
        ];

        // Figure out what data format to return to the client
        $produces = [
            'application/xml','application/json',
        ];
        try {
            $contentType = $request->headers->has('Content-Type') ? $request->headers->get('Content-Type') : $consumes[0];
            $requestFormat = $this->getOutputFormat($contentType, $consumes);
            if ($requestFormat === null) {
                // We can't consume the content that the client is sending us
                throw new RequestFormatNotSupportedException();
            }

            // Figure out what the client accepts
            $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
            $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
            if ($responseFormat === null) {
                throw new ResponseFormatNotSupportedException();
            }

            // Handle authentication

            // Read out all input parameter values into variables
            $body = $request->getContent();

            // Deserialize the input values that needs it
            $username = $this->deserialize($username, 'string', 'string');
            $body = $this->deserialize($body, 'Swagger\Server\Model\User', $requestFormat);

            // Validate the input values
            $validationMessages = [];
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts[] = new Assert\Type("string");
            $errors = $this->validate($username, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('username', $errors)
                );
            }
            $asserts = [];
            $asserts[] = new Assert\NotNull();
            $asserts = null;
            $errors = $this->validate($body, $asserts);
            if (count($errors) > 0) {
                $validationMessages = array_merge(
                    $validationMessages,
                    $this->formatValidationMessages('body', $errors)
                );
            }
            if (count($validationMessages) > 0) {
                throw new ParametersNotValidException('Bad Request', 0, null, $validationMessages);
            }

            
            // Make the call to the business logic
            $responseCode = 204;
            $responseHeaders = [];
            $response = $handler->updateUser($username, $body, $responseCode, $responseHeaders);

            // Set appropiate response type and message
            $responseType = $responses[$responseCode]['responseType'];

            // Assert that the output from business logic corresponds to response model
            $asserts = [];
            $asserts[] = new Assert\Type($responseType);
            $errors = $this->validator->validate($response, $asserts);
            if (count($errors) > 0) {
                throw new ResponseNotValidException('Unexpected Error', 0, null, $errors);
            }
        } catch (ParametersNotValidException $exception) {
            $responseCode = 400;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(400, $exception->getValidationErrors(), 'updateUser');
        } catch (ResponseFormatNotSupportedException $exception) {
            $responseCode = 406;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(406, [$exception->getMessage()], 'updateUser');
        } catch (RequestFormatNotSupportedException $exception) {
            $responseCode = 415;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(415, [$exception->getMessage()], 'updateUser');
        } catch (ResponseNotValidException $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::updateUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, $exception->getValidationErrors(), 'updateUser');
        } catch (Exception $exception) {
            $this->logger->error($exception, ['operation' => 'UserController::updateUser']);
            $responseCode = 500;
            $responseHeaders = [];
            $response = $handler->createErrorResponse(500, [$exception->getMessage()], 'updateUser');
        }
        if ($responseFormat === null) {
            $contentTypes = $this->sanitizeContentTypes($produces) ?: ['application/json'];
            $responseFormat = reset($contentTypes);
        }
        $message = isset($responses[$responseCode]['message']) ? $responses[$responseCode]['message'] : '';
        if ($response !== null) {
            $serializedResponse = $response;
            if ($responseFormat !== 'text/html') {
                $serializedResponse = $this->serialize($response, $responseFormat);
            }

            $responseObject = new Response(
                $serializedResponse,
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-Swagger-Message' => $message,
                    ]
                )
            );
            $this->logger->info($responseObject, ['operation' => 'UserController::updateUser']);
            return $responseObject;
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return UserApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('user');
    }
}
