name: 'Python Build'
description: 'build python project'
inputs:
  path:
    description: 'project root path'
    required: true
  job-name:
    description: 'Job name'
    required: true
outputs:
  logs:
    description: "logs"
    value: ${{ steps.build.outputs.logs }}
  path:
    description: "output path"
    value: ${{ steps.build.outputs.path }}
runs:
  using: "composite"
  steps:
    - id: build
      name: build
      run: |
        logfile=${{ inputs.job-name }}.log
        echo "::set-output name=logs::$(echo $logfile)"
        echo "::set-output name=path::$(echo generated/${{ inputs.job-name }})"
        echo -e "\n****** python ******\n" >> $logfile
        curdir=$(pwd)
        cd ${{ inputs.path }}
        echo -e "\n****** python setup and build ******\n" >> $curdir/$logfile
        python3 setup.py install --user | tee --append $curdir/$logfile
        pip3 install nose2 --user
        python3 -m nose2 | tee --append $curdir/$logfile
        cd ${curdir}
      shell: bash
