name: Test Framework

on:
  # execute on demand
  workflow_dispatch:
    branches: ["master", "test-framework", "3.0.0"]

jobs:

  # builds codegen cli and uploads its artifact
  build-codegen:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build codegen
        run: |
          mvn -q -B package -DskipTests
      - name: prepare codegen cli
        run: mkdir codegen-cli && cp modules/swagger-codegen-cli/target/swagger-codegen-cli.jar codegen-cli
      - name: upload codegen cli
        uses: actions/upload-artifact@v2
        with:
          name: codegen-cli
          path: codegen-cli

  # generate a javascript client V3 from petstore3.swagger.io OpenAPI definition
  generate-js-v3-petstore:

    needs: build-codegen

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Download codegen cli
        uses: actions/download-artifact@v2
        with:
          name: codegen-cli
      - name: generate
        id: generate
        continue-on-error: true
        uses: ./.github/actions/generate
        with:
          language: $LANGUAGE
          job-name: ${JOB_NAME}
          options: $OPTIONS
      - name: upload generate logs
        uses: actions/upload-artifact@v2
        with:
          name: generate_logs_${{ env.JOB_NAME }}
          path: ${{ steps.generate.outputs.logs }}
      - name: upload generated code
        if: contains(steps.generate.outcome, 'success')
        uses: actions/upload-artifact@v2
        with:
          name: generated_${{ env.JOB_NAME }}
          path: ${{ steps.generate.outputs.path }}
      - run: |
          echo ${{ steps.generate.outcome }} > generate_outcome_${{ env.JOB_NAME }}
      - name: upload generate outcome
        uses: actions/upload-artifact@v2
        with:
          name: generate_outcome_${{ env.JOB_NAME }}
          path: generate_outcome_${{ env.JOB_NAME }}
    env:
      LANGUAGE: "javascript"
      JOB_NAME: "js-petstore-v3"
      OPTIONS: " -DappName=PetstoreClient --additional-properties useES6=false"

  build-js-v3-petstore:

    needs: generate-js-v3-petstore

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: generated_${{ env.JOB_NAME }}
          # todo replace with job output
          path: generated/${{ env.JOB_NAME }}
      - name: Download logs
        uses: actions/download-artifact@v2
        with:
          name: generate_logs_${{ env.JOB_NAME }}
          #path: ${{ env.JOB_NAME }}.build.log
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: jsbuild
        id: jsbuild
        uses: ./.github/actions/jsbuild
        with:
          path: generated/${{ env.JOB_NAME }}
          job-name: ${{ env.JOB_NAME }}
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.jsbuild.outputs.logs }}
          path: ${{ steps.jsbuild.outputs.logs }}
    env:
      JOB_NAME: "js-petstore-v3"
